In [2]:
!pip install librosa
!pip install openpyxl

import os
import librosa
import numpy as np
from multiprocessing import Pool
from tqdm import tqdm
import traceback
import pandas as pd

Collecting librosa
  Downloading librosa-0.11.0-py3-none-any.whl.metadata (8.7 kB)
Collecting audioread>=2.1.9 (from librosa)
  Downloading audioread-3.1.0-py3-none-any.whl.metadata (9.0 kB)
Collecting numba>=0.51.0 (from librosa)
  Downloading numba-0.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.8 kB)
Requirement already satisfied: numpy>=1.22.3 in /opt/conda/lib/python3.12/site-packages (from librosa) (2.3.5)
Requirement already satisfied: scipy>=1.6.0 in /opt/conda/lib/python3.12/site-packages (from librosa) (1.16.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from librosa) (1.7.2)
Requirement already satisfied: joblib>=1.0 in /opt/conda/lib/python3.12/site-packages (from librosa) (1.5.2)
Requirement already satisfied: decorator>=4.3.0 in /opt/conda/lib/python3.12/site-packages (from librosa) (5.2.1)
Collecting soundfile>=0.12.1 (from librosa)
  Downloading soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting pooch>=1.1 (from librosa)
  Downloading pooch-1.8.2-py3-none-any.whl.metadata (10 kB)
Collecting soxr>=0.3.2 (from librosa)
  Downloading soxr-1.0.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: typing_extensions>=4.1.1 in /opt/conda/lib/python3.12/site-packages (from librosa) (4.15.0)
Collecting lazy_loader>=0.1 (from librosa)
  Downloading lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: msgpack>=1.0 in /opt/conda/lib/python3.12/site-packages (from librosa) (1.1.2)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from lazy_loader>=0.1->librosa) (25.0)
Collecting llvmlite<0.46,>=0.45.0dev0 (from numba>=0.51.0->librosa)
  Downloading llvmlite-0.45.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: platformdirs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from pooch>=1.1->librosa) (4.5.0)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/lib/python3.12/site-packages (from pooch>=1.1->librosa) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2025.10.5)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /opt/conda/lib/python3.12/site-packages (from soundfile>=0.12.1->librosa) (2.0.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.22)
Downloading librosa-0.11.0-py3-none-any.whl (260 kB)
Downloading audioread-3.1.0-py3-none-any.whl (23 kB)
Downloading lazy_loader-0.4-py3-none-any.whl (12 kB)
Downloading numba-0.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 102.9 MB/s  0:00:00
Downloading llvmlite-0.45.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 134.6 MB/s  0:00:00m0:00:0100:01
Downloading pooch-1.8.2-py3-none-any.whl (64 kB)
Downloading soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 115.6 MB/s  0:00:00
Downloading soxr-1.0.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (238 kB)
Installing collected packages: soxr, llvmlite, lazy_loader, audioread, soundfile, pooch, numba, librosa
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [librosa]m7/8 [librosa]]
Successfully installed audioread-3.1.0 lazy_loader-0.4 librosa-0.11.0 llvmlite-0.45.1 numba-0.62.1 pooch-1.8.2 soundfile-0.13.1 soxr-1.0.0
Requirement already satisfied: openpyxl in /opt/conda/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.12/site-packages (from openpyxl) (2.0.0)

In [3]:
df = pd.read_csv("/work/nlpminifolder/extracted_files/fma_small_merged.csv")

df.head()

,filepath,filename,track_id,audio_path,top_genres,num_labels,label_Rock,label_Electronic,label_Pop,label_Folk,label_Instrumental,label_HipHop,label_International,label_Classical,label_Jazz,label_Country,label_Blues,label_SoulRnB,mel_path
0,fma_small/018/018032.mp3,018032.mp3,18032,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,/work/NLP-mini-project/datasets/fma/fma_clean/...
1,fma_small/018/018037.mp3,018037.mp3,18037,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,/work/NLP-mini-project/datasets/fma/fma_clean/...
2,fma_small/018/018144.mp3,018144.mp3,18144,/datasets/fma/fma_clean/fma_selected/018/01814...,[10],1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,/work/NLP-mini-project/datasets/fma/fma_clean/...
3,fma_small/018/018159.mp3,018159.mp3,18159,/datasets/fma/fma_clean/fma_selected/018/01815...,[17],1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,/work/NLP-mini-project/datasets/fma/fma_clean/...
4,fma_small/018/018038.mp3,018038.mp3,18038,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,/work/NLP-mini-project/datasets/fma/fma_clean/...

In [4]:
df = df.drop(columns=["mel_path"])

In [5]:
def make_path(track_id):
    tid_str = f"{int(track_id):06d}"   # 000123
    folder = tid_str[:3]               # 000
    return f"music/fma_small/{folder}/{tid_str}.mp3"
df["path"] = df["track_id"].apply(make_path)
df.head()

,filepath,filename,track_id,audio_path,top_genres,num_labels,label_Rock,label_Electronic,label_Pop,label_Folk,label_Instrumental,label_HipHop,label_International,label_Classical,label_Jazz,label_Country,label_Blues,label_SoulRnB,path
0,fma_small/018/018032.mp3,018032.mp3,18032,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,music/fma_small/018/018032.mp3
1,fma_small/018/018037.mp3,018037.mp3,18037,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,music/fma_small/018/018037.mp3
2,fma_small/018/018144.mp3,018144.mp3,18144,/datasets/fma/fma_clean/fma_selected/018/01814...,[10],1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,music/fma_small/018/018144.mp3
3,fma_small/018/018159.mp3,018159.mp3,18159,/datasets/fma/fma_clean/fma_selected/018/01815...,[17],1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,music/fma_small/018/018159.mp3
4,fma_small/018/018038.mp3,018038.mp3,18038,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,music/fma_small/018/018038.mp3

In [6]:
#df = df.drop(columns=["filepath"])
df = df.drop(columns=["path"])
df.head()

,filepath,filename,track_id,audio_path,top_genres,num_labels,label_Rock,label_Electronic,label_Pop,label_Folk,label_Instrumental,label_HipHop,label_International,label_Classical,label_Jazz,label_Country,label_Blues,label_SoulRnB
0,fma_small/018/018032.mp3,018032.mp3,18032,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,fma_small/018/018037.mp3,018037.mp3,18037,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,fma_small/018/018144.mp3,018144.mp3,18144,/datasets/fma/fma_clean/fma_selected/018/01814...,[10],1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,fma_small/018/018159.mp3,018159.mp3,18159,/datasets/fma/fma_clean/fma_selected/018/01815...,[17],1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,fma_small/018/018038.mp3,018038.mp3,18038,/datasets/fma/fma_clean/fma_selected/018/01803...,[2],1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# 1) Waveform — load and pad/trim to 30s at 44.1 kHz
'''
import librosa
import numpy as np

TARGET_SR = 44100
TARGET_LEN = TARGET_SR * 30   # 30 seconds

def load_and_fix_waveform(path):
    y, sr = librosa.load(path, sr=TARGET_SR, mono=True)
    if len(y) < TARGET_LEN:
        y = np.pad(y, (0, TARGET_LEN - len(y)), mode="constant")
    else:
        y = y[:TARGET_LEN]
    return y.astype("float32")

import os

waveform_paths = []

for tid in df["track_id"].astype(int):
    tid6 = f"{tid:06d}"
    sub = tid6[:3]
    audio_path = f"../extracted_files/fma_small/{sub}/{tid6}.mp3"
    save_path = f"../extracted_files/waveforms/{tid6}.npy"

    if os.path.exists(audio_path):
        y = load_and_fix_waveform(audio_path)
        np.save(save_path, y)
        waveform_paths.append(save_path)
'''

In [ ]:
df["waveform_path"] = df["track_id"].apply(
    lambda x: f"/work/nlpminifolder/extracted_files/waveforms/{int(x):06d}.npy"
)

In [ ]:
df["waveform_exists"] = df["waveform_path"].apply(os.path.exists)
bad_shapes = df[df["waveform_exists"]].copy()

wrong = []
for idx, row in bad_shapes.iterrows():
    y = np.load(row["waveform_path"])
    if y.shape[0] != 1323000:
        wrong.append((row["track_id"], y.shape))

wrong[:10], len(wrong)

In [ ]:
df["waveform_exists"].value_counts()
# 2046 tracks have no waveform (not in fma_small)

In [ ]:
df = df[df["waveform_path"].apply(os.path.exists)].copy()
df.isnull().sum()

In [ ]:
# 2) Mel spectrogram

In [ ]:
# Mel spectrogram generation (same config as fma_transform_to_spectrograms.py)
'''
import os
import librosa
import numpy as np
from multiprocessing import Pool
from tqdm import tqdm
import traceback

INPUT_ROOT = "extracted_files/fma_small"
OUTPUT_ROOT = "mels"

SAMPLE_RATE = 32000
N_MELS = 128
WIN_LENGTH = int(0.025 * SAMPLE_RATE)  # 25ms
HOP_LENGTH = int(0.010 * SAMPLE_RATE)  # 10ms

for i in range(256):
    os.makedirs(os.path.join(OUTPUT_ROOT, f"{i:03d}"), exist_ok=True)


def process_file(task):
    in_path, out_path = task
    if os.path.exists(out_path):
        return f"SKIPPED {out_path}"
    try:
        y, sr = librosa.load(in_path, sr=SAMPLE_RATE, mono=True)
        mel = librosa.feature.melspectrogram(
            y=y, sr=sr, n_fft=WIN_LENGTH, hop_length=HOP_LENGTH,
            win_length=WIN_LENGTH, n_mels=N_MELS, power=2.0
        )
        np.save(out_path, librosa.power_to_db(mel, ref=np.max))
        return f"OK {out_path}"
    except Exception as e:
        error_msg = f"ERROR {in_path}: {repr(e)}"
        with open(os.path.join(OUTPUT_ROOT, "errors.log"), "a") as f:
            f.write(error_msg + "\n")
            f.write(traceback.format_exc() + "\n")
        return error_msg


tasks = []
for root, dirs, files in os.walk(INPUT_ROOT):
    for f in files:
        if not f.endswith(".mp3"):
            continue
        track_id = f[:-4]       # e.g. "093522"
        subfolder = track_id[:3]
        tasks.append((os.path.join(root, f), os.path.join(OUTPUT_ROOT, subfolder, track_id + ".npy")))

print("Found", len(tasks), "audio files.")

if __name__ == "__main__":
    num_workers = max(os.cpu_count() - 1, 1)
    with Pool(num_workers) as pool:
        for result in tqdm(pool.imap_unordered(process_file, tasks), total=len(tasks), ncols=100):
            pass
    print("Done! Mels saved to:", OUTPUT_ROOT)
'''

In [ ]:
def make_mel_path(track_id):
    tid = f"{int(track_id):06d}"
    folder = tid[:3]
    return f"/work/nlpminifolder/extracted_files/mels/{folder}/{tid}.npy"

df["mel_path"] = df["track_id"].apply(make_mel_path)

In [ ]:
df.head()

In [ ]:
df["mel_exists"] = df["mel_path"].apply(os.path.exists)
df["mel_exists"].value_counts()

In [ ]:
# 3) CQT spectrogram

In [ ]:
'''
INPUT_ROOT = "/work/nlpminifolder/extracted_files/fma_small"
OUTPUT_ROOT = "/work/nlpminifolder/extracted_files/cqt"

SAMPLE_RATE = 32000
HOP_LENGTH = int(0.010 * SAMPLE_RATE)

N_BINS = 128         # match mel shape for fair comparison
BINS_PER_OCTAVE = 16
FMIN = 32.7

os.makedirs(OUTPUT_ROOT, exist_ok=True)

mp3s = []
for root, dirs, files in os.walk(INPUT_ROOT):
    for f in files:
        if f.endswith(".mp3"):
            full_path = os.path.join(root, f)
            if os.path.isfile(full_path) and os.path.getsize(full_path) > 5000:
                mp3s.append(full_path)

print("MP3 files found:", len(mp3s))

for mp3 in tqdm(mp3s):
    track_id = os.path.splitext(os.path.basename(mp3))[0]
    out_path = os.path.join(OUTPUT_ROOT, track_id + ".npy")

    if os.path.exists(out_path):
        continue

    try:
        y, sr = librosa.load(mp3, sr=SAMPLE_RATE, mono=True)
        cqt = librosa.cqt(y, sr=sr, hop_length=HOP_LENGTH,
                          n_bins=N_BINS, bins_per_octave=BINS_PER_OCTAVE, fmin=FMIN)
        cqt_db = librosa.amplitude_to_db(np.abs(cqt), ref=np.max)
        np.save(out_path, cqt_db)
    except Exception as e:
        with open(os.path.join(OUTPUT_ROOT, "cqt_errors.log"), "a") as f:
            f.write(f"{mp3}: {repr(e)}\n")
            f.write(traceback.format_exc() + "\n\n")
        continue

print("Done. CQT saved to:", OUTPUT_ROOT)
'''

In [ ]:
def make_cqt_path(track_id):
    tid = f"{int(track_id):06d}"
    return f"/work/nlpminifolder/extracted_files/cqt/{tid}.npy"

df["cqt_path"] = df["track_id"].apply(make_cqt_path)
df.head()

In [ ]:
df["cqt_exists"] = df["cqt_path"].apply(os.path.exists)
df["cqt_exists"].value_counts()

In [ ]:
# Align input shapes — all representations padded/trimmed to 30s

In [ ]:
def pad_or_trim_2d(arr, target_time=3000):
    """Pad or trim mel/CQT along the time axis to target_time frames."""
    freq_bins, time_bins = arr.shape
    if time_bins < target_time:
        arr = np.pad(arr, ((0, 0), (0, target_time - time_bins)), mode="constant")
    elif time_bins > target_time:
        arr = arr[:, :target_time]
    return arr.astype("float32")

In [ ]:
def pad_or_trim_1d(arr, target_len):
    """Pad or trim waveform to target_len samples."""
    L = len(arr)
    if L < target_len:
        arr = np.pad(arr, (0, target_len - L), mode="constant")
    elif L > target_len:
        arr = arr[:target_len]
    return arr.astype("float32")

In [28]:
def process_folder(input_folder, pad_func, target):
    for root, dirs, files in os.walk(input_folder):
        for f in tqdm(files, desc=f"Processing {input_folder}"):
            if f.endswith(".npy"):
                full = os.path.join(root, f)
                arr = np.load(full)
                arr = pad_func(arr, target)
                np.save(full, arr)

In [ ]:
# Fix all three representations to the same duration
process_folder("/work/nlpminifolder/extracted_files/mels", pad_or_trim_2d, 3000)
process_folder("/work/nlpminifolder/extracted_files/cqt", pad_or_trim_2d, 3000)
TARGET_LEN = 44100 * 30
process_folder("/work/nlpminifolder/extracted_files/waveforms", pad_or_trim_1d, TARGET_LEN)

In [30]:
#checking the input shapes if it worked
def check_shapes(folder):
    shapes = set()
    for root, dirs, files in os.walk(folder):
        for f in files:
            if f.endswith(".npy"):
                arr = np.load(os.path.join(root, f))
                shapes.add(arr.shape)
    return shapes

print("MEL  :", check_shapes("/work/nlpminifolder/extracted_files/mels"))
print("CQT  :", check_shapes("/work/nlpminifolder/extracted_files/cqt"))
print("WAVE :", check_shapes("/work/nlpminifolder/extracted_files/waveforms"))

MEL  : {(128, 3000)}
CQT  : {(128, 3000)}
WAVE : {(1323000,)}

In [ ]:
# Save df_audio for the representation comparison notebook
'''
df_audio = df.drop(columns=["mel_exists", "waveform_exists", "cqt_exists"], errors="ignore")
output_path = "/work/nlpminifolder/extracted_files/df_audio.xlsx"
df_audio.to_excel(output_path, index=False)
print("Saved to:", output_path)
'''